# Generated by Django 4.2.6 on 2023-10-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_clock_partner_will'),
    ]

    operations = [
        migrations.CreateModel(
            name='Btc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation', models.IntegerField()),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Token/')),
                ('name', models.TextField()),
                ('title', models.TextField()),
            ],
        ),
    ]
