# Generated by Django 4.2.6 on 2023-10-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_btc_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='btc',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='btc',
            name='token',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
