# Generated by Django 4.2.6 on 2023-10-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_btc_title_btc_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contingency', models.IntegerField()),
                ('investor', models.IntegerField()),
                ('legal', models.IntegerField()),
                ('development', models.IntegerField()),
            ],
        ),
    ]
