# Generated by Django 4.2.6 on 2023-10-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Paper/')),
                ('text', models.TextField(max_length=255)),
                ('white', models.CharField(max_length=255)),
                ('privace', models.CharField(max_length=255)),
                ('terms', models.CharField(max_length=255)),
                ('one', models.CharField(max_length=255)),
            ],
        ),
    ]
