# Generated by Django 4.2.6 on 2023-10-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_contact_world_alter_team_hobby_alter_team_insta'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='photo',
            field=models.ImageField(default=1, upload_to='world/'),
            preserve_default=False,
        ),
    ]
