# Generated by Django 4.2.6 on 2023-10-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_world_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('you', models.CharField(max_length=25)),
                ('tw', models.CharField(max_length=25)),
                ('fc', models.CharField(max_length=25)),
                ('insta', models.CharField(max_length=25)),
            ],
        ),
    ]
