# Generated by Django 4.2.6 on 2023-10-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_about_alter_world_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='choose/')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Trey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=155)),
                ('title', models.CharField(max_length=155)),
                ('img', models.ImageField(upload_to='Trey/')),
                ('photo', models.ImageField(upload_to='Trey/')),
            ],
        ),
    ]
