# Generated by Django 4.2.6 on 2023-10-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_choose_trey'),
    ]

    operations = [
        migrations.AddField(
            model_name='trey',
            name='rasm',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
