# Generated by Django 4.2.6 on 2023-10-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=155)),
                ('safe', models.CharField(max_length=155)),
                ('day', models.CharField(max_length=155)),
                ('software', models.CharField(max_length=155)),
                ('trial', models.CharField(max_length=155)),
                ('work', models.CharField(max_length=155)),
            ],
        ),
    ]
