# Generated by Django 4.2.6 on 2023-10-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_frequent'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequent',
            name='title',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
    ]
