# Generated by Django 4.2.6 on 2023-10-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_frequent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequent',
            name='iphone',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frequent',
            name='less',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frequent',
            name='mobile',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
    ]
